//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: System.Reflection.AssemblyProduct("MongoDB.Messaging")]
[assembly: System.Reflection.AssemblyCompany("LoreSoft")]
[assembly: System.Reflection.AssemblyCopyright("Copyright © 2017 LoreSoft")]
[assembly: System.Reflection.AssemblyConfiguration("Release")]
[assembly: System.Reflection.AssemblyVersion("1.7.0.0")]
[assembly: System.Reflection.AssemblyFileVersion("1.7.0.0")]
[assembly: System.Reflection.AssemblyInformationalVersion("1.7.0.0")]
[assembly: System.Runtime.InteropServices.ComVisible(false)]



internal sealed partial class ThisAssembly {
    
    internal const string AssemblyProduct = "MongoDB.Messaging";
    
    internal const string AssemblyCompany = "LoreSoft";
    
    internal const string AssemblyCopyright = "Copyright © 2017 LoreSoft";
    
    internal const string AssemblyConfiguration = "Release";
    
    internal const string AssemblyVersion = "1.7.0.0";
    
    internal const string AssemblyFileVersion = "1.7.0.0";
    
    internal const string AssemblyInformationalVersion = "1.7.0.0";
    
    private ThisAssembly() {
    }
}
